// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKcPuor5e90b__h3EO_E1EF2ZJRJDPTOw',
    appId: '1:444620404094:web:9c226a10c4b6bd72fa6f2f',
    messagingSenderId: '444620404094',
    projectId: 'cashew-budget-app-23736',
    authDomain: 'cashew-budget-app-23736.firebaseapp.com',
    storageBucket: 'cashew-budget-app-23736.firebasestorage.app',
    measurementId: 'G-T2V05D4QRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ROvBi_5MUMXF7BZSGwyGiCWsKw0NfMo',
    appId: '1:444620404094:android:2bded9b69263f4f7fa6f2f',
    messagingSenderId: '444620404094',
    projectId: 'cashew-budget-app-23736',
    storageBucket: 'cashew-budget-app-23736.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBibAwY1UBIWR4guyZbw-d5VNJDZcklh0k',
    appId: '1:444620404094:ios:7d6412ee4fc46578fa6f2f',
    messagingSenderId: '444620404094',
    projectId: 'cashew-budget-app-23736',
    storageBucket: 'cashew-budget-app-23736.firebasestorage.app',
    androidClientId: '444620404094-ff71svihsbdqtgglvipgdvca69mpkso3.apps.googleusercontent.com',
    iosClientId: '444620404094-ct2ekv0l1vjituav0r01uccdkdir9tah.apps.googleusercontent.com',
    iosBundleId: 'com.budget.tracker-app',
  );

}